config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bookings, only: [:index]
  resources :users
  resources :plants do
    collection do
      get "search"
      get :my
    end
    resources :bookings, only: [:create, :edit, :update, :destroy]
  end
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  # before_create :check_overlapping_date

  belongs_to :user
  belongs_to :plant

  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :start_equal_to_end
  validate :no_overlap
  validate :no_past_bookings
  validate :start_after_end

  def start_equal_to_end
    return unless self.start_date == self.end_date
    errors.add(:end_date, "must be different from start date")
  end

  def start_after_end
    return unless self.start_date > self.end_date
    errors.add(:end_date, "must be after start date")
  end

  def no_overlap
    plant.bookings.each do |booking|
        errors.add(:start_date, "is not available") if booking.dates.include? start_date
        errors.add(:end_date, "is not available") if booking.dates.include? end_date
    end
    return errors.empty?
  end

  def no_past_bookings
    return unless self.start_date < Date.today
    errors.add(:start_date, "must not be in the past")
  end



  def start_time
    self.start_date
  end

  def end_time
    self.end_date - 1
  end

  def dates
    self.start_date..self.end_date
  end
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :user
  has_many :bookings
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  CATEGORY = ["Cactus", "Succulent", "Fern", "Tree", "Bush", "Flower", "Herb", "Bonsai", "Other"]

  validates :title, presence: true
  validates :description, presence: true
  validates :photo, presence: true
  validates :cost, presence: true
  validates :plant_type, presence: true
  validates :address, presence: true
  mount_uploader :photo, PhotoUploader

  def self.search(search)
    where("title ILIKE ? OR description ILIKE ? OR care ILIKE ? OR plant_type ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  end

  def booked_dates
    array = []
    bookings = Booking.where(plant:self.id)
    bookings.each do |booking|
      range = (booking.start_date..booking.end_date).to_a
      range.each do |r|
        array << r
      end
    end
    return array
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookings, dependent: :destroy
  has_many :plants, dependent: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: [:index, :search], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [:index, :search], unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo, :photo_cache])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :first_name, :last_name, :photo, :photo_cache])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = policy_scope(Booking).where(user: current_user).order(created_at: :desc)
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @plant = Plant.find(params[:plant_id])
    @booking.plant = @plant
    authorize @plant
    if @booking.save
      flash[:notice] = "Thanks for booking!"
      respond_to do |format|
        format.html { redirect_to plant_path(@plant) }
        format.js  # <-- will render `app/views/bookings/create.js.erb`
      end
    else
      @bookings = Booking.where(plant:@plant)
      respond_to do |format|
        format.html { render 'plants/show' }
        format.js  # <-- idem
      end
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    redirect_to root_path, notice: "This booking has been deleted."
  end

  private

  def booking_params
    params.require(:booking).permit(:plant_id, :start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @plants = policy_scope(Plant).order(created_at: :desc)
    if params[:search]
      @plants = Plant.search(params[:search]).order("created_at DESC")
    else
      @plants = Plant.all.order("created_at DESC")
    end
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :search, :show]
  before_action :find_plant, only: [:show, :update, :destroy, :edit]

  def index
    @plants = policy_scope(Plant).order(created_at: :desc)
    @plants = @plants.where.not(latitude: nil, longitude: nil)
    @markers = @plants.map do |plant|
      {
        lat: plant.latitude,
        lng: plant.longitude,
        icon: 'https://res.cloudinary.com/trembylene/image/upload/v1524193056/pin.png',
        infoWindow: {
          content: "<a href='/plants/#{plant.id}'><img src='#{plant.photo}' class='photo_markers' /><h5> $#{plant.cost}/day</h5><strong>#{plant.title}</strong><br>"
        }
      }
    end
  end

  def my
    @plants = policy_scope(current_user.plants).order(title: :asc)
    authorize @plants
  end

  def search
    if params[:search]
      @plants = policy_scope(Plant.search(params[:search]))
    else
      @plants = policy_scope(Plant)
    end
    @plants = @plants.order("created_at DESC").group_by { |p| p.plant_type }
    # @plants = @plants.where.not(latitude: nil, longitude: nil)
    @markers = @plants.values.flatten.map do |plant|
      {
        lat: plant.latitude,
        lng: plant.longitude,
        id: plant.id,
        icon: 'https://res.cloudinary.com/trembylene/image/upload/v1524193056/pin.png',
        infoWindow: {
          content: "<a href='#{plant.id}'><img src='#{plant.photo}' class='photo_markers' /><h5> $#{plant.cost}/day</h5><strong>#{plant.title}</strong><br>"
        }
      }
    end
  end

  def new
    @plant = Plant.new
    authorize @plant
  end

  def create
    @plant = Plant.new(plant_params)
    authorize @plant
    @plant.user_id = current_user.id
    if @plant.save
      redirect_to my_plants_path(@plant)
    else
      render :new
    end
  end

  def show
    @booking = Booking.new(start_date: Date.today, end_date: Date.today, plant: @plant)
    @bookings = Booking.where(plant:@plant)
    authorize @plant
    @markers = [{
      lat: @plant.latitude,
      lng: @plant.longitude,
      icon: 'https://res.cloudinary.com/trembylene/image/upload/v1524193056/pin.png',
      infoWindow: {
          content: "<a href='#{@plant.id}'><img src='#{@plant.photo}' class='photo_markers' /><h5> $#{@plant.cost}/day</h5><strong>#{@plant.title}</strong><br>"
      }
    }]
  end

  def edit
    authorize @plant
  end

  def update
    @plant.update(plant_params)
    authorize @plant
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: 'Your plant was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    authorize @plant
    @plant.destroy
    redirect_to plants_path
  end

  private

  def find_plant
    @plant = Plant.find(params[:id])
  end

  def plant_params
    params.require(:plant).permit(:title, :address, :description, :care, :photo, :photo_cache, :cost, :plant_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= asset_path 'favicon/apple-touch-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= asset_path 'favicon/apple-touch-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= asset_path 'favicon/apple-touch-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= asset_path 'favicon/apple-touch-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= asset_path 'favicon/apple-touch-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= asset_path 'favicon/apple-touch-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= asset_path 'favicon/apple-touch-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= asset_path 'favicon/apple-touch-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="192x192" href="<%= asset_path 'favicon/android-chrome-192x192.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-TileImage" content="<%= asset_path 'favicon/mstile-144x144.png' %>">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/bookings/_form.html.erb
<%= simple_form_for([plant, booking], remote: user_signed_in?) do |f| %>
          <%= f.error_notification %>
          <div class="form-inputs">
            <%= f.hidden_field :cost, :value => "#{plant.cost}" %>
            <%= f.input :start_date, as: :string, label: "From", required: true, input_html: { class: "datepicker", data: {:'date-dates-disabled' => plant.booked_dates }, :onchange => "calculateTotal()" } %>
            <%= f.input :end_date, as: :string, label: "To", required: true, input_html: { class: "datepicker", data: {:'date-dates-disabled' => plant.booked_dates }, :onchange => "calculateTotal()" } %>
          </div>
          <div>
            <ul class="list-inline">
              <li><p>$<%= plant.cost %> x</p></li>
              <li id="days"></li>
              <li><p>days</p></li>
            </ul>
            <ul class="list-inline">
            <li><p>Total = $</p></li>
            <li id="cost"></li>
            </ul>
          </div>
          <div class="form-actions btn-book">
            <%= f.button :submit, "Book" %>
          </div>
        <% end %>

app/views/bookings/create.js.erb
function refreshForm(innerHTML) {
  const newBookingForm = document.getElementById('plant-booking');
  newBookingForm.innerHTML = innerHTML;
}

<% if @booking.errors.any? %>
  refreshForm('<%= j render "bookings/form", plant: @plant, booking: @booking %>');
<% else %>
  window.location = "<%= bookings_path %>"
<% end %>


setupUI();

app/views/bookings/index.html.erb
<h2 class="text-center">Your bookings</h2>

<div class="bookings">
  <div class="container">
    <% @bookings.each do |booking| %>
      <div class="row">
        <div class="col-xs-12 col-sm-8">
          <h3 class="booking-title"><%= (booking.plant.title).capitalize %> booking information</h3>
          <h4>Plant owner</h4>
          <div class="booking">
            <p><em>Owner: </em><%= booking.plant.user.first_name %> <%= booking.plant.user.last_name %></p>
            <p><em>Contact details: </em><%= booking.plant.user.email %></p>
            <%= link_to "Plant details", plant_path(booking.plant_id) %>
          </div>
          <h4>Details</h4>
          <div class="booking">
            <p><em>Start date: </em><%= booking.start_date %></p>
            <p><em>End date: </em><%= booking.end_date %></p>
            <p><em>Daily cost: </em><%= booking.plant.cost %></p>
            <p><em>Total cost: </em><%= ((booking.end_date - booking.start_date).to_i)*booking.plant.cost %></p>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4">
          <div class="card-booking" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
           url('<%= cl_image_path booking.plant.photo, height: 200, width: 350, crop: :fill %>')">
          </div>
        </div>
      </div>
      <hr>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= render 'application/favicon' %>
    <title>Netflix and Dill</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous"> -->
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link href="https://fonts.googleapis.com/css?family=Gugi|Open+Sans" rel="stylesheet">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>

    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag 'calendar' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-banner" style="background-image: url(<%= asset_path 'plant-banner.jpg' %>)">
  <div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1 class="title-banner text-center"><span>Netflix and Dill</span></h1>
      <h2 class="byline-banner text-center"><span>Plants to rent for all occasions</span></h2>
      <%= link_to "Find plants to rent", plants_path, class: "btn btn-success" %>
    </div>
  </div>
  </div>
</div>
<div class="container-plants">
<div class="container">
  <div class="row">
    <% @plants.each do |plant| %>
      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <div class="card">
          <div class="plant" style="background-image: url(<%= plant.photo %>);">
            <div class="card-category"><%= plant.plant_type %></div>
          </div>
          <div class="card-description">
            <h2><%= link_to plant.title, plant_path(plant) %></h2>
          </div>
          <%= link_to "", plant_path(plant), class: "card-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/plants/_form.html.erb
<%= simple_form_for [@plant] do |f| %>
  <%= f.error_notification %>
  <div class="container">
    <div class="row">
      <div class="form-group col-sm-8 col-sm-offset-2">
        <div class="form-inputs">
          <%= f.input :title, required: true, autofocus: true %>
          <%= f.input :description, required: true %>
          <%= f.input :care, required: true  %>
          <%= f.input :cost, required: true  %>
          <%= f.input :plant_type, collection: Plant::CATEGORY, as: :select, required: true %>
          <%= f.input :address, required: true %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
        </div>


        <div class="form-actions">
          <%= f.button :submit, "Complete" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/plants/edit.html.erb
<div class="forms">

<h2 class="text-center">Edit your plant post</h2>

<%= render 'form' %>

</div>

app/views/plants/index.html.erb
<div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
></div>

<div class="card-container">
  <div class="container">
    <div class="row">
      <% @plants.each do |plant| %>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
          <div class="card">
            <div class="plant" style="background-image: url(<%= plant.photo %>);">
              <div class="card-category"><%= plant.plant_type %></div>
            </div>
            <div class="card-description">
              <h2><%= link_to plant.title, plant_path(plant) %></h2>
             </div>
            <%= link_to "", plant_path(plant), class: "card-link"  %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/plants/my.html.erb
<h2 class="text-center">My Plants</h2>
<div class="my_plants">
  <div class="container">
    <% @plants.each do |plant| %>
      <div class="row">
        <div class="col-xs-12 col-sm-8">
          <h3 class="my_plants-title"><%= (plant.title).capitalize %> </h3>
          <h4>Plant owner</h4>
          <div class="my_plants">
            <p><em>Location: </em><%= plant.address %></p>
            <p><em>Registered: </em><%= plant.created_at %></p>
            <p><em>Last Update: </em><%= plant.updated_at %></p>
            <%= link_to "Plant details", plant_path(plant.id) %>
          </div>

        </div>
        <div class="col-xs-12 col-sm-4">
          <div class="card-booking" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
           url('<%= cl_image_path plant.photo, height: 200, width: 350, crop: :fill %>')">
          </div>
        </div>
      </div>
      <hr>
    <% end %>
  </div>
</div>

app/views/plants/new.html.erb
<div class="forms">

<h2 class="text-center">Add your plant!</h2>

<%= render 'form' %>

</div>

app/views/plants/search.html.erb
<% if @plants.blank? %>
  <div class="container">
    <h2>Sorry. There are no plants containing the term <%= params[:search] %>.</h2>
  </div>
<% end %>

<div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
></div>

<% if @plants.values.flatten.count != Plant.count %>
  <h1>Search Results (<%= @plants.values.flatten.count %>)</h1>
<% end %>

<div class="card-container">
  <div class="container">
    <% @plants.each do |plant_type, plants| %>
      <h3><%= plant_type %></h3>
      <div class="row">
        <% plants.each do |plant| %>
          <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
            <div class="card">
              <div class="plant" style="background-image: url(<%= plant.photo %>);">
                <div class="card-category"><%= plant.plant_type %></div>
              </div>
              <div class="card-description">
                <h2><%= link_to plant.title, plant_path(plant) %></h2>
              </div>
              <%= link_to "", plant_path(plant), class: "card-link" %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/plants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-lg-6">
      <div class="plant-show" style="background-image: url(<%= @plant.photo %>);">
      </div>
    </div>
    <div class="col-xs-12 col-lg-6">
      <div class="plant-description">
        <h3>
          <%= @plant.title %>
          <% if @plant.user == current_user %>
            <small>
              <%= link_to "", edit_plant_path(@plant), :class => "fa fa-edit fa-lg" %>
              <%= link_to "", plant_path(@plant),
                :class => "fa fa-trash-o fa-lg",
                method: :delete,
                data: { confirm: "Are you sure?" } %>
            </small>
          <% end %>
        </h3>
        <h4><%= @plant.description %></h4>
        <br>
        <h4><em>Details</em></h4>
        <p><strong>Plant care:</strong> <%= @plant.care %></p>
        <p><strong>Plant type:</strong> <%= @plant.plant_type %></p>
        <p><strong>Cost: </strong>$<%= @plant.cost %></p>
      </div>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-xs-12 col-lg-6">
      <div id="map" style="width: 80%; height: 350px;" data-markers="<%= @markers.to_json %>">
      </div>
    </div>
    <div class="col-xs-12 col-lg-6">
      <div class="booking-title">
        <h3>Book this plant</h3>
      <div class="plant-booking", id="plant-booking">
        <%= render 'bookings/form', plant: @plant, booking: @booking  %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
     <i class="fa fa-leaf"></i></i>
  </div>
</div>
 -->

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <div>
    <!-- Logo -->
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo-dill.png", height: 50 %>
    <% end %>

    <!-- Search -->
    <%= form_tag(search_plants_path, :method => "get", id: "search", class: "navbar-form navbar-right hidden-xs hidden-sm") do %>
      <div class="form-group">
        <%= text_field_tag :search, params[:search], class: "navbar-form-control", placeholder: "Search" %>
      </div>
      <%= button_tag(type: "submit", class: "btn btn-default navbar-btn") do %>
        <i class="fa fa-search"></i>
      <% end %>
    <% end %>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to "Rent a plant", plants_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Advertise your plant", new_plant_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to bookings_path do %>
                <i class="fa fa-bookmark-o"></i>  <%= t(".your_bookings", default: "Your bookings") %>
              <% end %>
            </li>
            <li>
              <%= link_to my_plants_path do %>
                <i class="fa fa-tree"></i>  <%= t(".my_plants", default: "My plants") %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' }, class:"fas fa-trash-alt" do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <% if user_signed_in? %>
      <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= form_tag(search_plants_path, :method => "get", id: "search-form", class: "navbar-wagon-item navbar-wagon-link", type:"search") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search" %>
          <% end %>
        </li>
        <li>
          <%= link_to plants_path do %>
            <i class="fa fa-tree"></i> <%= t(".rent_plants", default: "Rent a plant") %>
          <% end %>
        </li>
        <li>
          <%= link_to my_plants_path do %>
            <i class="fa fa-tree"></i>  <%= t(".my_plants", default: "My plants") %>
          <% end %>
        </li>
        <li>
          <%= link_to new_plant_path do %>
            <i class="fa fa-leaf"></i> <%= t(".new_plant", default: "Advertise your plant") %>
          <% end %>
        </li>
        <li>
          <%= link_to bookings_path do %>
            <i class="fa fa-bookmark-o"></i>  <%= t(".your_bookings", default: "Your bookings") %>
          <% end %>
        </li>
        <li>
          <%= link_to edit_user_registration_path do %>
            <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
        <div class="dropdown">
          <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= form_tag(search_plants_path, :method => "get", id: "search-form", class: "navbar-wagon-item navbar-wagon-link", type:"search") do %>
                <%= text_field_tag :search, params[:search], placeholder: "Search" %>
              <% end %>
            </li>
            <li>
              <%= link_to plants_path do %>
                <i class="fa fa-pagelines"></i> <%= t(".rent_plants", default: "Rent a plant") %>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path do %>
                <i class="fa fa-sign-in"></i> <%= t(".sign_in", default: "Login") %>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path do %>
                <i class="fa fa-user-plus"></i> <%= t(".sign_up", default: "Sign up") %>
              <% end %>
            </li>
          </ul>
        </div>
    <% end %>
  </div>
</div>